/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PoliceFrontDeskRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CustomerServiceOrganization;
import Business.Organization.Organization;
import Business.Organization.PoliceFrontDeskOrganization;
import Business.Organization.PoliceOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalToCustomerServiceWorkRequest;
import Business.WorkQueue.PoliceToCustomerServiceWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mrunalini
 */
public class PoliceFrontDeskWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private PoliceFrontDeskOrganization policeFrontDeskOrganization;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;

    /**
     * Creates new form PoliceFrontDeskWorkAreaJPanel
     */
    public PoliceFrontDeskWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization policeFrontDeskOrganization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecoSystem = business;
        this.policeFrontDeskOrganization = (PoliceFrontDeskOrganization) policeFrontDeskOrganization;
        this.enterprise = enterprise;
        populateTable();
                valueLabel.setText(enterprise.getName());

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) policeFrontJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : policeFrontDeskOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof HospitalToCustomerServiceWorkRequest) {
                System.out.print("");
            } else if (request instanceof PoliceToCustomerServiceWorkRequest) {
                System.out.print("");
            } else {

                Object[] row = new Object[6];

                row[1] = request.getPatientName();
                row[0] = request;
                row[2] = request.getPriority();
                row[3] = request.getSender();
                row[4] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row[5] = request.getStatus();

                model.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        policeFrontJTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnSendToPolice = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        policeFrontJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Name", "Priority", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(policeFrontJTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 80, 683, 173));

        jButton1.setText("Assign to me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 352, -1, -1));

        btnSendToPolice.setText("Send to Police");
        btnSendToPolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToPoliceActionPerformed(evt);
            }
        });
        jPanel1.add(btnSendToPolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 352, 123, -1));

        jButton2.setText("Send to Save Lives");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 408, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 127, 30));

        valueLabel.setText("<value>");
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 158, 26));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = policeFrontJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }
                JOptionPane.showMessageDialog(null, "You are now handling this case.", "Message To You.", JOptionPane.INFORMATION_MESSAGE);


        WorkRequest req = (WorkRequest) policeFrontJTable.getValueAt(selectedRow, 0);
        req.setReceiver(userAccount);
        req.setStatus("Processing");

        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSendToPoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToPoliceActionPerformed
        int row = policeFrontJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WorkRequest request = (WorkRequest) policeFrontJTable.getValueAt(row, 0);
        if (request.getStatus().equals("Received")) {
            JOptionPane.showMessageDialog(null, "Please assign the request to yourself before sending to the police.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            WorkRequest request1 = new WorkRequest();

            request1.setLocation(request.getLocation());
            request1.setPriority(request.getPriority());
            request1.setSender(userAccount);
            request1.setStatus("Received");
            request1.setPatientName(request.getPatientName());

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof PoliceOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request1);
                userAccount.getWorkQueue().getWorkRequestList().add(request1);
            }

        }        JOptionPane.showMessageDialog(null, "Sent to police.", "Message To You.", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendToPoliceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = policeFrontJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
         WorkRequest request = (WorkRequest) policeFrontJTable.getValueAt(row, 0);
         if (request.getStatus().equals("Received")) {
            JOptionPane.showMessageDialog(null, "Please assign the request to yourself before sending to the police.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
          JOptionPane.showMessageDialog(null, "Sent to Save Lives.", "Information", JOptionPane.INFORMATION_MESSAGE);
           
            int size1 = policeFrontDeskOrganization.getWorkQueue().getWorkRequestList().size();

            if (policeFrontDeskOrganization.getWorkQueue().getWorkRequestList() != null && !policeFrontDeskOrganization.getWorkQueue().getWorkRequestList().isEmpty()) {

                WorkRequest request1 = policeFrontDeskOrganization.getWorkQueue().getWorkRequestList().get(size1 - 1);

                if (request1 instanceof PoliceToCustomerServiceWorkRequest) {
                    PoliceToCustomerServiceWorkRequest wr2 = new PoliceToCustomerServiceWorkRequest();

                    wr2.setPatientName(request1.getPatientName());
                    wr2.setLocation(request1.getLocation());
                    wr2.setDescription(((PoliceToCustomerServiceWorkRequest) request1).getDescription());
                    wr2.setOthers(((PoliceToCustomerServiceWorkRequest) request1).getOthers());
                    wr2.setReason(((PoliceToCustomerServiceWorkRequest) request1).getReason());
                    wr2.setDamage(((PoliceToCustomerServiceWorkRequest) request1).getDamage());

                    Organization org = null;
                    for (Network network : ecoSystem.getNetworkList()) {

                        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                if (organization instanceof CustomerServiceOrganization) {
                                    org = organization;
                                    break;
                                }
                            }
                            

                        }
                    }
                    if (org != null) {
                                org.getWorkQueue().getWorkRequestList().add(wr2);

                            }

                }
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendToPolice;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable policeFrontJTable;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
