/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PoliceRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PoliceOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalToCustomerServiceWorkRequest;
import Business.WorkQueue.PoliceToCustomerServiceWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mrunalini
 */
public class PoliceWorkAreaJPanel extends javax.swing.JPanel {

    private PoliceOrganization policeOrganization;
    private JPanel userProcessContainer;
    private UserAccount userAccount;

    private Organization organization;
    private Enterprise enterprise;

    /**
     * Creates new form PoliceWorkAreaJPanel
     */
    public PoliceWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization policeOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;

        this.policeOrganization = (PoliceOrganization) policeOrganization;
        this.enterprise = enterprise;
        populateTable();
                valueLabel.setText(enterprise.getName());

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPolice2.getModel();

        model.setRowCount(0);

        for (WorkRequest request : policeOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof HospitalToCustomerServiceWorkRequest) {
                System.out.print("");
            } else if (request instanceof PoliceToCustomerServiceWorkRequest) {
                System.out.print("");
            } else {

                Object[] row = new Object[6];

                row[2] = request.getPatientName();

                row[1] = request.getPriority();
                row[0] = request;
                row[3] = request.getSender();
                row[4] = row[4] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row[5] = request.getStatus();

                model.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolice2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPolice2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Priority", "Patient Name", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPolice2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 561, 136));

        jButton1.setText("Assign To Me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jButton2.setText("Generate Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 127, 30));

        valueLabel.setText("<value>");
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 158, 26));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = tblPolice2.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }
        JOptionPane.showMessageDialog(null, "You are now handling this case.", "Message To You.", JOptionPane.INFORMATION_MESSAGE);


        WorkRequest req = (WorkRequest) tblPolice2.getValueAt(selectedRow, 0);
        req.setReceiver(userAccount);
        req.setStatus("Processing");

        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = tblPolice2.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest) tblPolice2.getValueAt(row, 0);
        if (request.getStatus().equals("Received")) {
            JOptionPane.showMessageDialog(null, "Please assign the request to yourself before treatment.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            PoliceReportJPanel policeReportJPanel = new PoliceReportJPanel(userProcessContainer, userAccount, policeOrganization, enterprise);
            userProcessContainer.add("PoliceReportJPanel", policeReportJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPolice2;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
