/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.HospitalHelpDeskOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalToCustomerServiceWorkRequest;
import Business.WorkQueue.PoliceToCustomerServiceWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mrunalini
 */
public class DoctorReportJPanel extends javax.swing.JPanel {

    private DoctorOrganization doctorOrganization;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    WorkRequest request;

    /**
     * Creates new form DoctorReportJPanel
     */
    public DoctorReportJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization doctorOrganization, Enterprise enterprise, WorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        //this.ecoSystem = ecoSystem;
        this.doctorOrganization = (DoctorOrganization) doctorOrganization;
        this.enterprise = enterprise;
        this.request = request;

        int size = doctorOrganization.getWorkQueue().getWorkRequestList().size();

        if (doctorOrganization.getWorkQueue().getWorkRequestList() != null && !doctorOrganization.getWorkQueue().getWorkRequestList().isEmpty()) {

            WorkRequest request1 = doctorOrganization.getWorkQueue().getWorkRequestList().get(size - 1);
            if (request1 instanceof WorkRequest) {

                String patientName = request1.getPatientName().getEmployee().getName();
                String location = request1.getLocation();

                txtLocation.setText(location);
                txtName.setText(patientName);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaInjuries = new javax.swing.JTextArea();
        cmbLifeSaved = new javax.swing.JComboBox<>();
        btnSaved = new javax.swing.JButton();
        txtCondition = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 49, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Life saved");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 121, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Location");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 189, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Condition");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Injuries");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 253, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 53, 237, -1));
        jPanel2.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 176, 237, -1));

        txtAreaInjuries.setColumns(20);
        txtAreaInjuries.setLineWrap(true);
        txtAreaInjuries.setRows(5);
        jScrollPane1.setViewportView(txtAreaInjuries);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 253, 237, -1));

        cmbLifeSaved.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbLifeSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLifeSavedActionPerformed(evt);
            }
        });
        jPanel2.add(cmbLifeSaved, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 118, 237, -1));

        btnSaved.setText("SAVE");
        btnSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavedActionPerformed(evt);
            }
        });
        jPanel2.add(btnSaved, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 465, 146, -1));
        jPanel2.add(txtCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 397, 237, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 465, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cmbLifeSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLifeSavedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLifeSavedActionPerformed

    private void btnSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavedActionPerformed
        // TODO add your handling code here:
        request.setStatus("Processed");

        int size1 = doctorOrganization.getWorkQueue().getWorkRequestList().size();

        if (doctorOrganization.getWorkQueue().getWorkRequestList() != null && !doctorOrganization.getWorkQueue().getWorkRequestList().isEmpty()) {

            WorkRequest request1 = doctorOrganization.getWorkQueue().getWorkRequestList().get(size1 - 1);

            if ((request1 instanceof HospitalToCustomerServiceWorkRequest || request1 instanceof PoliceToCustomerServiceWorkRequest)) {
                System.out.println("");
            } else {
                String lifeSaved = cmbLifeSaved.getSelectedItem().toString();

                String loc = request1.getLocation();
                HospitalToCustomerServiceWorkRequest hcswr = new HospitalToCustomerServiceWorkRequest();
                hcswr.setPatientName(request1.getPatientName());
                hcswr.setLocation(loc);
                hcswr.setLifeSaved(lifeSaved);
                hcswr.setInjuryDescription(txtAreaInjuries.getText());
                hcswr.setCondition(txtCondition.getText());

                Organization org = null;

                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof HospitalHelpDeskOrganization) {

                        org = organization;
                        break;
                    }

                }
                if (org != null) {

                    if (hcswr instanceof HospitalToCustomerServiceWorkRequest) {
                        org.getWorkQueue().getWorkRequestList().add(hcswr);
                    }
                }

            }

        }

        userAccount.getEmployee().setAvailability("Yes");
                JOptionPane.showMessageDialog(null, "Report Generated.", "Message To You.", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnSavedActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSaved;
    private javax.swing.JComboBox<String> cmbLifeSaved;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaInjuries;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
